- hosts: [mesos-slave]

  roles:
    - { role: 'ansible-mesos', mesos_version: "0.25.0", mesos_ip: "{{ ansible_enp0s8.ipv4.address }}", mesos_quorum: "2", zookeeper_hostnames: "{{ groups.zookeeper | join(':' + zookeeper_client_port + ',')  }}:{{ zookeeper_client_port  }}", mesos_install_mode: 'slave', mesos_cluster_name: 'mesos-play' }


                