- hosts: all
  sudo: no
  gather_facts: no
  remote_user: root

  tasks:
    - name: install ssh key
      authorized_key: user=root key="{{ lookup('file', '/root/.ssh/id_rsa.pub') }}" state=present

    - name: /etc/hosts 
      lineinfile: dest=/etc/hosts line="{{ item }}"
      with_items:
        - "10.0.15.11 node1"
        - "10.0.15.12 node2"
        - "10.0.15.13 node3"
        - "10.0.15.14 node4"
        - "10.0.15.15 node5"

